version: '3.8'

services:
    app:
        build:
            context: .  # Contexto de build do Dockerfile na mesma pasta
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ../:/var/www  # Mapeia o código do projeto Laravel da pasta acima
            - ./cache:/var/www/storage/framework/cache  # Cache do Laravel
            - ./sessions:/var/www/storage/framework/sessions  # Sessões
        networks:
            - app-network
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=http://your-domain.com  # Altere para seu domínio
            - DB_CONNECTION=mysql
            - DB_HOST=your-external-db-host  # Altere para o host do seu DB externo
            - DB_PORT=3306
            - DB_DATABASE=your_database  # Nome do banco de dados
            - DB_USERNAME=your_username  # Nome de usuário do DB
            - DB_PASSWORD=your_password  # Senha do DB
        depends_on:
            - php-fpm

    php-fpm:
        image: php:8.3-fpm
        container_name: php_fpm
        volumes:
            - ../:/var/www  # Mapeia o código do projeto Laravel da pasta acima
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www  # Mapeia o código do projeto Laravel da pasta acima
        networks:
            - app-network
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
